import { GoogleGenerativeAI } from '@google/generative-ai';
import { createClient } from '@supabase/supabase-js';
import nodemailer from 'nodemailer';

// Give the function room for several retries before Vercel times it out.
export const config = { maxDuration: 60 };

// Gemini sometimes returns a transient 503 ("high demand") or 429 (rate limit)
// when a model is briefly overloaded. Without retries that surfaced to the
// user as a scary "서버 오류: 500", and the tool felt hit-or-miss. We try a
// whole sequence of models in order: when one is overloaded (or unavailable),
// we move on to the next. A demand spike almost never hits every model at the
// same instant, so going wide across models is what makes this reliable —
// more than just waiting on a single one. The first two entries retry the
// best model before stepping down to lighter/older ones.
const MIRROR_MODELS = [
  'gemini-2.5-flash',
  'gemini-2.5-flash',
  'gemini-2.0-flash',
  'gemini-2.5-flash-lite',
  'gemini-1.5-flash',
];

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Only a bad or forbidden API key is truly fatal — for anything else (overload,
// a model that this key can't access, a temporary network blip) we keep going
// to the next model so a single failing model can't sink the whole request.
function isFatalGeminiError(err) {
  const msg = err && err.message ? err.message : '';
  return /api[_ ]?key|permission[ _]?denied|unauthorized|\b401\b|\b403\b/i.test(msg);
}

// Was the failure just temporary overload? Used to pick a softer user message.
function isTransientGeminiError(err) {
  const msg = err && err.message ? err.message : '';
  return /\b(429|500|503)\b/.test(msg) ||
    /overloaded|high demand|service unavailable|rate limit|try again later/i.test(msg);
}

// Returns the generated mirror text, walking the model list until one answers.
// Throws the last error only after every model has been tried (or immediately
// on a fatal API-key error).
async function generateMirrorText(genAI, request) {
  let lastErr;
  for (let i = 0; i < MIRROR_MODELS.length; i++) {
    if (i > 0) await sleep(600 * i); // 0, 600, 1200, 1800, 2400ms between tries
    try {
      const model = genAI.getGenerativeModel({ model: MIRROR_MODELS[i] });
      const result = await model.generateContent(request);
      const text = result.response.text();
      if (text && text.trim()) return text;
      lastErr = new Error('Gemini API returned an empty response');
    } catch (err) {
      lastErr = err;
      if (isFatalGeminiError(err)) throw err; // key problem: no point retrying
      // otherwise keep trying the next model in the list
    }
  }
  throw lastErr;
}

export default async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const body = req.body;

    // Validate input
    const requiredFields = ['userId', 'sensations', 'oneWord', 'scene', 'sceneSensation', 'sceneInterpretation', 'voiceA', 'voiceB', 'oneSentence', 'sentenceFeeling', 'tomorrowAction', 'gratitude'];

    for (const field of requiredFields) {
      if (!body[field] || (typeof body[field] === 'string' && !body[field].trim())) {
        return res.status(400).json({ success: false, error: `Missing: ${field}` });
      }
    }

    // Extract user name and contact if provided
    const userName = (body.userName || body['이름'] || '').trim();
    const userContact = (body.userContact || body['연락처'] || body.contact || '').trim();
    const greetingName = userName || '○○';

    // Generate mirror prompt
    const prompt = `당신은 거울입니다. 고객이 쓴 기록을 정렬하고 비춰주는 것이 전부입니다.

[입력된 기록]
- 감각: ${body.sensations}
- 한 단어: ${body.oneWord}
- 장면: ${body.scene}
- 그때 감각: ${body.sceneSensation}
- 내 해석: ${body.sceneInterpretation}
- 목소리 A: ${body.voiceA}
- 목소리 B: ${body.voiceB}
- 오늘의 한 문장: ${body.oneSentence}
- 문장 읽을 때: ${body.sentenceFeeling}
- 내일 행동: ${body.tomorrowAction}
- 감사: ${Array.isArray(body.gratitude) ? body.gratitude.join(', ') : body.gratitude}

[규칙]
1. 고객의 단어를 그대로 사용하되, 문단처럼 자연스럽게 정렬
2. 반복되는 패턴 1가지를 짚고, 괄호로 의미를 기울임체로 표현 (단 한 번만)
3. 마지막 문단에서 "평온함을 찾게 하는" 내용 추가 (판단/조언/해석 없음)
4. 금지: 명상, 소마틱, 치유, 회복, 성장, 코칭, 이모지, 동기부여
5. 출력: ${greetingName}님, [정돈된 기록] [패턴 비춤] [마지막 문단] — 이어
6. 반드시 첫 줄을 "${greetingName}님,"으로 시작한다 (○○ 같은 빈 칸 금지)`;

    // Call Gemini API (with retry + fallback on transient overload).
    // Gemini 2.5 Flash is a thinking model: reasoning tokens count toward
    // maxOutputTokens, so a small budget gets eaten by thinking and the
    // visible answer is truncated to a line or two. Give a generous budget.
    const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GEMINI_API_KEY);
    const mirrorText = await generateMirrorText(genAI, {
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: {
        maxOutputTokens: 8192,
        temperature: 0.9,
      },
    });

    // Save to Supabase. sessions.id is a uuid generated by the DB, and
    // mirrors.session_id is a uuid FK to it — so we must insert the session
    // first, read back the generated uuid, then insert the mirror with it.
    // (The previous code passed a `session-<timestamp>` string as the FK,
    // which violated the uuid FK and silently failed, leaving mirrors empty.)
    const today = new Date().toISOString().split('T')[0];
    let sessionId = null;
    let mirrorId = null;

    if (process.env.SUPABASE_URL && process.env.SUPABASE_KEY) {
      const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

      const { data: sessionRow, error: sessionError } = await supabase
        .from('sessions')
        .insert([{
          user_id: body.userId,
          user_name: userName || null,
          user_contact: userContact || null,
          recorded_at: today,
          sensations: body.sensations,
          one_word: body.oneWord,
          scene: body.scene,
          scene_sensation: body.sceneSensation,
          scene_interpretation: body.sceneInterpretation,
          voice_a: body.voiceA,
          voice_b: body.voiceB,
          one_sentence: body.oneSentence,
          sentence_feeling: body.sentenceFeeling,
          tomorrow_action: body.tomorrowAction,
          gratitude: Array.isArray(body.gratitude) ? body.gratitude : [body.gratitude],
        }])
        .select('id')
        .single();

      if (sessionError) {
        console.error('Session save error:', sessionError.message);
      } else if (sessionRow) {
        sessionId = sessionRow.id;

        const { data: mirrorRow, error: mirrorError } = await supabase
          .from('mirrors')
          .insert([{
            session_id: sessionId,
            mirror_text: mirrorText,
            metadata: { contact: userContact || null },
          }])
          .select('id')
          .single();

        if (mirrorError) {
          console.error('Mirror save error:', mirrorError.message);
        } else if (mirrorRow) {
          mirrorId = mirrorRow.id;
        }
      }
    }

    // Send email if user contact provided
    if (userContact && userContact.trim()) {
      try {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: parseInt(process.env.SMTP_PORT || '587'),
          secure: process.env.SMTP_SECURE === 'true',
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        await transporter.sendMail({
          from: process.env.SMTP_FROM || process.env.SMTP_USER,
          to: userContact,
          subject: '이어 — 당신의 거울 글',
          text: mirrorText,
          html: `<div style="font-family: sans-serif; color: #333; line-height: 1.6; max-width: 600px; margin: 0 auto;">
            <div style="border-left: 4px solid #b9784f; padding: 20px; background: #f9f7f2; margin: 20px 0; border-radius: 4px;">
              <p style="margin-top: 0; white-space: pre-wrap; color: #5c574e;">${mirrorText.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>
            </div>
            <p style="color: #9a9489; font-size: 13px; text-align: center; margin-top: 40px;">
              © 2026 이어 — 당신의 말을 정돈해 비춰드려요
            </p>
          </div>`,
        });

        console.log('Email sent successfully to:', userContact);
      } catch (emailError) {
        console.error('Email send error:', emailError.message);
        // Don't fail the main request if email fails
      }
    }

    return res.status(200).json({
      success: true,
      mirrorText,
      mirrorId,
      sessionId,
    });

  } catch (error) {
    console.error('Error:', error.message);
    // If the AI was simply overloaded, tell the user it's temporary and to
    // try again in a moment — never show a raw technical message.
    const transient = isTransientGeminiError(error);
    return res.status(transient ? 503 : 500).json({
      success: false,
      transient,
      error: transient
        ? '지금은 잠시 붐비고 있어요. 잠깐 두었다 다시 보내 주세요.'
        : '잠깐 문제가 생겼어요. 잠시 뒤에 다시 보내 주세요.',
    });
  }
};
