{
  "description": "Manipulates events and other calendar data.",
  "ownerName": "Google",
  "revision": "20260614",
  "servicePath": "calendar/v3/",
  "basePath": "/calendar/v3/",
  "baseUrl": "https://www.googleapis.com/calendar/v3/",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/workspace/calendar/firstapp",
  "id": "calendar:v3",
  "name": "calendar",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "version": "v3",
  "batchPath": "batch/calendar/v3",
  "rootUrl": "https://www.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/calendar.events.freebusy": {
          "description": "See the availability on Google calendars you have access to"
        },
        "https://www.googleapis.com/auth/calendar.events": {
          "description": "View and edit events on all your calendars"
        },
        "https://www.googleapis.com/auth/calendar.acls.readonly": {
          "description": "See the sharing permissions of Google calendars you own"
        },
        "https://www.googleapis.com/auth/calendar.freebusy": {
          "description": "View your availability in your calendars"
        },
        "https://www.googleapis.com/auth/calendar.calendarlist": {
          "description": "See, add, and remove Google calendars you’re subscribed to"
        },
        "https://www.googleapis.com/auth/calendar.events.owned.readonly": {
          "description": "See the events on Google calendars you own"
        },
        "https://www.googleapis.com/auth/calendar.calendars": {
          "description": "See and change the properties of Google calendars you have access to, and create secondary calendars"
        },
        "https://www.googleapis.com/auth/calendar": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/calendar.acls": {
          "description": "See and change the sharing permissions of Google calendars you own"
        },
        "https://www.googleapis.com/auth/calendar.events.readonly": {
          "description": "View events on all your calendars"
        },
        "https://www.googleapis.com/auth/calendar.events.owned": {
          "description": "See, create, change, and delete events on Google calendars you own"
        },
        "https://www.googleapis.com/auth/calendar.app.created": {
          "description": "Make secondary Google calendars, and see, create, change, and delete events on them"
        },
        "https://www.googleapis.com/auth/calendar.readonly": {
          "description": "See and download any calendar you can access using your Google Calendar"
        },
        "https://www.googleapis.com/auth/calendar.calendars.readonly": {
          "description": "See the title, description, default time zone, and other properties of Google calendars you have access to"
        },
        "https://www.googleapis.com/auth/calendar.events.public.readonly": {
          "description": "See the events on public calendars"
        },
        "https://www.googleapis.com/auth/calendar.calendarlist.readonly": {
          "description": "See the list of Google calendars you’re subscribed to"
        },
        "https://www.googleapis.com/auth/calendar.settings.readonly": {
          "description": "View your Calendar settings"
        }
      }
    }
  },
  "title": "Calendar API",
  "resources": {
    "settings": {
      "methods": {
        "get": {
          "path": "users/me/settings/{setting}",
          "description": "Returns a single user setting.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "id": "calendar.settings.get",
          "httpMethod": "GET"
        },
        "watch": {
          "supportsSubscription": true,
          "description": "Watch for changes to Settings resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "httpMethod": "POST",
          "path": "users/me/settings/watch",
          "id": "calendar.settings.watch"
        },
        "list": {
          "description": "Returns all user settings for the authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "supportsSubscription": true,
          "id": "calendar.settings.list",
          "httpMethod": "GET",
          "path": "users/me/settings"
        }
      }
    },
    "acl": {
      "methods": {
        "update": {
          "id": "calendar.acl.update",
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "description": "Updates an access control rule.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls"
          ],
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "calendar.acl.patch",
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "description": "Updates an access control rule. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls"
          ],
          "httpMethod": "PATCH"
        },
        "list": {
          "supportsSubscription": true,
          "description": "Returns the rules in the access control list for the calendar.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls",
            "https://www.googleapis.com/auth/calendar.acls.readonly"
          ],
          "httpMethod": "GET",
          "path": "calendars/{calendarId}/acl",
          "id": "calendar.acl.list"
        },
        "insert": {
          "id": "calendar.acl.insert",
          "httpMethod": "POST",
          "description": "Creates an access control rule.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls"
          ],
          "path": "calendars/{calendarId}/acl"
        },
        "watch": {
          "description": "Watch for changes to ACL resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls",
            "https://www.googleapis.com/auth/calendar.acls.readonly"
          ],
          "supportsSubscription": true,
          "httpMethod": "POST",
          "path": "calendars/{calendarId}/acl/watch",
          "id": "calendar.acl.watch"
        },
        "get": {
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "httpMethod": "GET",
          "id": "calendar.acl.get",
          "description": "Returns an access control rule.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls",
            "https://www.googleapis.com/auth/calendar.acls.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "calendar.acl.delete",
          "description": "Deletes an access control rule.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls"
          ],
          "path": "calendars/{calendarId}/acl/{ruleId}"
        }
      }
    },
    "events": {
      "methods": {
        "delete": {
          "description": "Deletes an event.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "id": "calendar.events.delete",
          "httpMethod": "DELETE",
          "path": "calendars/{calendarId}/events/{eventId}"
        },
        "insert": {
          "path": "calendars/{calendarId}/events",
          "httpMethod": "POST",
          "description": "Creates an event.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "id": "calendar.events.insert"
        },
        "patch": {
          "id": "calendar.events.patch",
          "path": "calendars/{calendarId}/events/{eventId}",
          "httpMethod": "PATCH",
          "description": "Updates an event. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ]
        },
        "quickAdd": {
          "description": "Creates an event based on a simple text string.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "httpMethod": "POST",
          "id": "calendar.events.quickAdd",
          "path": "calendars/{calendarId}/events/quickAdd"
        },
        "move": {
          "description": "Moves an event to another calendar, i.e. changes an event's organizer. Note that only default events can be moved; birthday, focusTime, fromGmail, outOfOffice and workingLocation events cannot be moved.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "id": "calendar.events.move",
          "httpMethod": "POST",
          "path": "calendars/{calendarId}/events/{eventId}/move"
        },
        "get": {
          "path": "calendars/{calendarId}/events/{eventId}",
          "description": "Returns an event based on its Google Calendar ID. To retrieve an event using its iCalendar ID, call the events.list method using the iCalUID parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "httpMethod": "GET",
          "id": "calendar.events.get"
        },
        "watch": {
          "path": "calendars/{calendarId}/events/watch",
          "httpMethod": "POST",
          "description": "Watch for changes to Events resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "supportsSubscription": true,
          "id": "calendar.events.watch"
        },
        "list": {
          "path": "calendars/{calendarId}/events",
          "supportsSubscription": true,
          "description": "Returns events on the specified calendar.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "httpMethod": "GET",
          "id": "calendar.events.list"
        },
        "instances": {
          "path": "calendars/{calendarId}/events/{eventId}/instances",
          "httpMethod": "GET",
          "supportsSubscription": true,
          "description": "Returns instances of the specified recurring event.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.events.instances"
        },
        "import": {
          "path": "calendars/{calendarId}/events/import",
          "description": "Imports an event. This operation is used to add a private copy of an existing event to a calendar. Only events with an eventType of default may be imported.\nDeprecated behavior: If a non-default event is imported, its type will be changed to default and any event-type-specific properties it may have will be dropped.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "httpMethod": "POST",
          "id": "calendar.events.import"
        },
        "update": {
          "description": "Updates an event.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.owned"
          ],
          "httpMethod": "PUT",
          "path": "calendars/{calendarId}/events/{eventId}",
          "id": "calendar.events.update"
        }
      }
    },
    "calendarList": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "calendar.calendarList.list",
          "supportsSubscription": true,
          "description": "Returns the calendars on the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.calendarlist",
            "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "path": "users/me/calendarList"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing calendar on the user's calendar list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist"
          ],
          "path": "users/me/calendarList/{calendarId}",
          "id": "calendar.calendarList.patch"
        },
        "update": {
          "id": "calendar.calendarList.update",
          "path": "users/me/calendarList/{calendarId}",
          "description": "Updates an existing calendar on the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist"
          ],
          "httpMethod": "PUT"
        },
        "delete": {
          "description": "Removes a calendar from the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist"
          ],
          "httpMethod": "DELETE",
          "id": "calendar.calendarList.delete",
          "path": "users/me/calendarList/{calendarId}"
        },
        "get": {
          "path": "users/me/calendarList/{calendarId}",
          "description": "Returns a calendar from the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist",
            "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "httpMethod": "GET",
          "id": "calendar.calendarList.get"
        },
        "insert": {
          "description": "Inserts an existing calendar into the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.calendarlist"
          ],
          "id": "calendar.calendarList.insert",
          "httpMethod": "POST",
          "path": "users/me/calendarList"
        },
        "watch": {
          "path": "users/me/calendarList/watch",
          "httpMethod": "POST",
          "description": "Watch for changes to CalendarList resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.calendarlist",
            "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "supportsSubscription": true,
          "id": "calendar.calendarList.watch"
        }
      }
    },
    "calendars": {
      "methods": {
        "delete": {
          "id": "calendar.calendars.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendars"
          ],
          "path": "calendars/{calendarId}"
        },
        "insert": {
          "description": "Creates a secondary calendar.\nThe authenticated user for the request is made the data owner of the new calendar.\n\nNote: We recommend to authenticate as the intended data owner of the calendar. You can use domain-wide delegation of authority to allow applications to act on behalf of a specific user. Don't use a service account for authentication. If you use a service account for authentication, the service account is the data owner, which can lead to unexpected behavi[...]",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendars"
          ],
          "id": "calendar.calendars.insert",
          "httpMethod": "POST",
          "path": "calendars"
        },
        "get": {
          "description": "Returns metadata for a calendar.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendars",
            "https://www.googleapis.com/auth/calendar.calendars.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.calendars.get",
          "httpMethod": "GET",
          "path": "calendars/{calendarId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates metadata for a calendar. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendars"
          ],
          "path": "calendars/{calendarId}",
          "id": "calendar.calendars.patch"
        },
        "clear": {
          "path": "calendars/{calendarId}/clear",
          "id": "calendar.calendars.clear",
          "httpMethod": "POST",
          "description": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.calendars"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates metadata for a calendar.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendars"
          ],
          "path": "calendars/{calendarId}",
          "id": "calendar.calendars.update"
        }
      }
    },
    "colors": {
      "methods": {
        "get": {
          "path": "colors",
          "id": "calendar.colors.get",
          "httpMethod": "GET",
          "description": "Returns the color definitions for calendars and events.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist",
            "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ]
        }
      }
    },
    "freebusy": {
      "methods": {
        "query": {
          "path": "freeBusy",
          "httpMethod": "POST",
          "id": "calendar.freebusy.query",
          "description": "Returns free/busy information for a set of calendars.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.freebusy",
            "https://www.googleapis.com/auth/calendar.readonly"
          ]
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "httpMethod": "POST",
          "id": "calendar.channels.stop",
          "description": "Stop watching resources through this channel",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.acls",
            "https://www.googleapis.com/auth/calendar.acls.readonly",
            "https://www.googleapis.com/auth/calendar.app.created",
            "https://www.googleapis.com/auth/calendar.calendarlist",
            "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.freebusy",
            "https://www.googleapis.com/auth/calendar.events.owned",
            "https://www.googleapis.com/auth/calendar.events.owned.readonly",
            "https://www.googleapis.com/auth/calendar.events.public.readonly",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "path": "channels/stop"
        }
      }
    }
  },
  "ownerDomain": "google.com"
}
